# Name: Chenying Wang
# Email: chenying.wang@usc.edu
# USC ID: ****-****-**
# Date: Friday, February 28, 2020
MAKEFILE_BASE = ../build/Makefile.base

PROJECT_NAME = stitch
TYPE = APP
LIBS = common
INC_DIR = /usr/local/include/opencv4
3RD_PARTY_LIBS = opencv_core opencv_features2d opencv_xfeatures2d

include $(MAKEFILE_BASE)
