# Name: Chenying Wang
# Email: chenying.wang@usc.edu
# USC ID: ****-****-**
# Date: Friday, January 24, 2020
MAKEFILE_BASE = ../build/Makefile.base

PROJECT_NAME = demosaic
TYPE = APP
LIBS = common

include $(MAKEFILE_BASE)
