#!/bin/bash

# Name: Chenying Wang
# Email: chenying.wang@usc.edu
# USC ID: ****-****-**
# Date: Friday, February 28, 2020

PWD=${1}

SUCCESS="0"
ERROR="1"

PYTHON3="python3"
BIN_PATH="${PWD}/bin"

OUTPUT_IMAGE_PATH="${INPUT_IMAGE_PATH}/result"
OUTPUT_PATH="${INPUT_IMAGE_PATH}/out"

#### Warp Config ####
WARP="0"
WARP_BIN="${BIN_PATH}/warp"
WARP_INPUT_HEDWIG="${INPUT_IMAGE_PATH}/hedwig.raw"
WARP_INPUT_RACCOON="${INPUT_IMAGE_PATH}/raccoon.raw"
WARP_INPUT_BB8="${INPUT_IMAGE_PATH}/bb8.raw"
WARP_WIDTH="512"
WARP_HEIGHT="512"
WARP_CHANNEL="3"

#### Stitch Config ####
STITCH="1"
STITCH_BIN="${BIN_PATH}/stitch"
STITCH_INPUT_LEFT="${INPUT_IMAGE_PATH}/left.raw"
STITCH_INPUT_MIDDLE="${INPUT_IMAGE_PATH}/middle.raw"
STITCH_INPUT_RIGHT="${INPUT_IMAGE_PATH}/right.raw"
STITCH_WIDTH="480"
STITCH_HEIGHT="720"
STITCH_CHANNEL="3"

#### Morph Config ####
MORPH="1"
MORPH_BIN="${BIN_PATH}/morph"
MORPH_INPUT_FAN="${INPUT_IMAGE_PATH}/fan.raw"
MORPH_WIDTH_FAN="558"
MORPH_HEIGHT_FAN="558"
MORPH_INPUT_CUP="${INPUT_IMAGE_PATH}/cup.raw"
MORPH_WIDTH_CUP="315"
MORPH_HEIGHT_CUP="356"
MORPH_INPUT_MAZE="${INPUT_IMAGE_PATH}/maze.raw"
MORPH_WIDTH_MAZE="558"
MORPH_HEIGHT_MAZE="558"
MORPH_INPUT_STARS="${INPUT_IMAGE_PATH}/stars.raw"
MORPH_WIDTH_STARS="640"
MORPH_HEIGHT_STARS="480"
MORPH_INPUT_PCB="${INPUT_IMAGE_PATH}/PCB.raw"
MORPH_WIDTH_PCB="372"
MORPH_HEIGHT_PCB="239"
MORPH_THRESHOLD_PCB="60"
MORPH_INPUT_GEAR="${INPUT_IMAGE_PATH}/Geartooth.raw"
MORPH_WIDTH_GEAR="250"
MORPH_HEIGHT_GEAR="250"
MORPH_CHANNEL="1"
MORPH_STAGE1_MASKS="${PWD}/config/stage1_masks.csv"
MORPH_STAGE2_MASKS="${PWD}/config/stage2_masks.csv"

#### Plot Config ####
PLOT="1"
