# Name: Chenying Wang
# Email: chenying.wang@usc.edu
# USC ID: ****-****-**
# Date: Friday, March 20, 2020
MAKEFILE_BASE = ../build/Makefile.base

PROJECT_NAME = feature
TYPE = APP
LIBS = common
INC_DIR = /usr/local/include/opencv4
3RD_PARTY_LIBS = opencv_core opencv_features2d opencv_xfeatures2d opencv_imgcodecs opencv_imgproc

include $(MAKEFILE_BASE)
