MAKEFILE_BASE = ../../../build/MakefileBase.mk

PROJECT_NAME = postprocess
TYPE = APP
LIBS = jpeg_lib jpeg_6b_lib graph common
3RD_PARTY_LIBS = opencv_core opencv_imgcodecs opencv_imgproc
INC_DIR = /usr/local/include/opencv4

include $(MAKEFILE_BASE)
