# Name: Chenying Wang
# Email: chenying.wang@usc.edu
# USC ID: ****-****-**
# Date: Friday, February 28, 2020
MAKEFILE_BASE = ../build/Makefile.base

PROJECT_NAME = common
TYPE = LIB

include $(MAKEFILE_BASE)
