# Name: Chenying Wang
# Email: chenying.wang@usc.edu
# USC ID: ****-****-**
# Date: Friday, February 28, 2020
MAKEFILE_BASE = ../build/Makefile.base

PROJECT_NAME = morph
TYPE = APP
LIBS = common

include $(MAKEFILE_BASE)
