# Name: Chenying Wang
# Email: chenying.wang@usc.edu
# USC ID: ****-****-**
# Date: Friday, February 14, 2020
MAKEFILE_BASE = ../build/Makefile.base

PROJECT_NAME = edge
TYPE = APP
LIBS = common
INC_DIR = /usr/local/include/opencv4
3RD_PARTY_LIBS = opencv_core opencv_imgproc

include $(MAKEFILE_BASE)
